/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
 
  programmingSidebar: [
    {
      type: 'category',
      label: 'Programming',
      items: ['intro'],
    },
  ],
  macrosSidebar: [
    {
      type: 'category',
      label: 'Macros',
      items: ['macros-intro'],
    },
    {
      type: 'category',
      label: 'Validation',
      items: ['macros-validation/comparenobs'],
    },
    {
      type: 'category',
      label: 'SDTM',
      items: ['macros-sdtm/sdtm-pre', 'macros-sdtm/sdtm-post'],
    },

  ],
  
};

module.exports = sidebars;
